### ISSUE TITLE
Bitcoin cash and Zec sync issue

### ISSUE THREAD

**Issue by ibexnet** [horizontalsystems/unstoppable-wallet-ios#3100] opened 2021-05-21 07:37 UTC
Hi everybody,
I recently installed the app, version 0.20.1.
I created an Zcash and Bitcoin cash wallet and it not still syncing since 3 days.
The Zcash wallet just say "syncing..." and some time report a warning icon "no internet".
The Bitcoin cash yesterday start syncing and show some progress but now report "Syncing... 0% until May 6, 2021"
I need to make some transaction on these wallets and I can't, there is something that I can do to fix?

**Comment by esengulov** [comment] 2021-05-24 06:16
> Hi everybody,
> I recently installed the app, version 0.20.1.
> I created an Zcash and Bitcoin cash wallet and it not still syncing since 3 days.
> The Zcash wallet just say "syncing..." and some time report a warning icon "no internet".
> The Bitcoin cash yesterday start syncing and show some progress but now report "Syncing... 0% until May 6, 2021"
> I need to make some transaction on these wallets and I can't, there is something that I can do to fix?

hi, the issue with Bitcoin Cash was fixed in version 0.21 which is due this week. It's ready but goes through testing at the time being.

As for the Zcash, the sync works but the speed is very slow. And on top of that the syncing spinner doesn't show the state of the progress as well. We are aware of both issues and addressing them now in version 0.22.

**Comment by Dianaaiym** [comment] 2021-07-14 09:54
We could not reproduce and there is no answer from you.
Reopen the ticket if necessary

**Closed by Dianaaiym** 2021-07-14 09:54 UTC
