### ISSUE TITLE
TRX sync issues

### ISSUE THREAD

**Issue by serrq** [horizontalsystems/unstoppable-wallet-ios#5120] opened 2023-07-30 16:31 UTC
Android 13
OnePlus CPH2399
UW 0.33.3

Is there an other API chain option to get sync?

![1000036478](https://github.com/horizontalsystems/unstoppable-wallet-ios/assets/113377431/2ce588b0-3e92-437b-84b5-12574dcb3823)

**Comment by esengulov** [comment] 2023-07-31 07:44
duplicate of https://github.com/horizontalsystems/unstoppable-wallet-android/issues/6316, being resolved

**Closed by esengulov** 2023-07-31 07:44 UTC
