### ISSUE TITLE
Hacked network crashes Unstoppable/swift when installed on iOS iPod touch.

### ISSUE THREAD

**Issue by kristoffer-paulsson** [horizontalsystems/unstoppable-wallet-ios#5056] opened 2023-07-09 20:47 UTC
I am an Targeted Individual, I have Unstoppable with my real wallet installed and configured on an iPod touch 7 with latest iOS available for that model. When Connected to local network over WiFi and when entering my unlock pin code inside the wallet crashes after some time, a fem seconds. This does not happen when I am offline, or even after turning WiFi off, so obviously it's an online thing. Maybe the Swift implementation isn't fully secure against payloads when calling the blockchain getting online wallet data.

Hope you can solve the issue, or maybe better if you tell me how to send crashdumps.

Best regards
Paulsson TI!

**Comment by ealymbaev** [comment] 2023-07-10 06:03
You can send crash logs to support.unstoppable@protonmail.com

Here is the instruction on how to fetch crash logs from your iOS device:

https://developer.apple.com/documentation/xcode/acquiring-crash-reports-and-diagnostic-logs

**Comment by kristoffer-paulsson** [comment] 2023-07-10 14:07
Do you have an invitation code for TestFlight with current app.

Regards

Paulsson TI

**Comment by saphirblanc** [comment] 2023-07-10 17:23
Hello,
Just wanted to say I’m encountering exactly the same issue. I open the app and after like 3-5 seconds it’s crashing. Both on Wifi and 4G, and not occurring when mobile data/wifi are disabled.

**Comment by ealymbaev** [comment] 2023-07-11 05:31
@kristoffer-paulsson @saphirblanc 

I see crashes related to sync of Dash blockchain. Could you please approve that you have Dash enabled in your wallets?

**Comment by saphirblanc** [comment] 2023-07-11 05:38
Yes, dash is enabled.

**Comment by ealymbaev** [comment] 2023-07-11 05:42
@saphirblanc 

Thanks, the issue is identified and will be fixed asap. We will release a hotfix very soon.

**Comment by kristoffer-paulsson** [comment] 2023-07-11 06:12
I can confirm that I har Dash enabled too, and by disabling Dash the crash didn't happen, also enabling Dash and syncing again causes the crash!

**Comment by ealymbaev** [comment] 2023-07-11 09:42
@kristoffer-paulsson @saphirblanc 

The issue is fixed and hotfix is already released. The new version (0.33.2) should be available on AppStore as soon as it is approved by reviewer.

**Closed** 2023-07-12 10:19 UTC
Labels: bug, hotfix
